# -*- mode: ruby -*-
# vi: set ft=ruby :

# /**
# * <div class="p">
# * See documentation on <a
# * href="/documentation/vagabond/dev/Understanding-Configuration-Resolution">understanding
# * confugiration resolution for the details of how the <a
# * href="/documentation/vagabond/dev/Environment-Runtime-Primer#Runtime-Configuration">machine
# * level configuration is bounded and interacts with the template defined
# * configuration.
# * </div>
# */
require "#{File.expand_path(File.dirname(__FILE__))}/machine-config.rb"

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", "2048"]
  end
end

Vagrant.configure("1") do |config|
  # First, we check our required inputs
  if defined? $ip == nil
    raise 'Configuration variable must be defined by file \'machine_config.rb\' in same directory as this file before template may be executed.'
  end

  config.vm.box = "whitebox-opensuse-12_3x64-desktop"
  config.vm.box_url = "file:///#{File.expand_path('~')/vagabond/data/boxes/whitebox-opensuse-12_3x64-desktop.box"

  config.ssh.username = 'user'
#  config.ssh.private_key_path = '/home/user/vagabond/secure_id_rsa'
end
